version: 2.0

jobs:
  build:
    docker:
      - image: cimg/node:20.12.0

    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@10"

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: eslint
          command: npm run lint

      - run:
          name: build
          command: npm run build

      - run:
          name: run vitest
          command: npm run test
